USE [AUTOMATION 2]
--INSERT,DELETE,UPDATE
	INSERT INTO SALE (SPID,SerialNO,CustomerID,SDate) VALUES ('400','123123123','5001',null);
	INSERT INTO CAR_PACKAGE VALUES('123123123',1002,1);
	INSERT INTO CAR_OPTION VALUES('222222222',203,2);

	DELETE FROM CAR_OPTION WHERE OptNO='102' AND SerialNO='123123123'
	DELETE FROM CAR WHERE SerialNO='234234234'
	DELETE FROM CAR_PACKAGE WHERE SerialNO='333333333' AND PackageNO=3000
	
	UPDATE SALESPERSON SET SPPhone='05423655998' WHERE SPID='400'
	UPDATE OPTIONS SET OptionPrice=1399.99 WHERE OptionNO='201'
	UPDATE MODEL SET Price=28999.99 WHERE ModelNO=2;
-- SELECT STATEMENTS
	-- AYNI MARKAYA AÝT MARKALARI VE MODELLERÝ ÝSME GÖRE SIRALAMA
	SELECT Manufacture,ModelName
	FROM MODEL
	ORDER BY Manufacture,ModelName

	--400 numaralý personelin sattýðý araç sayýsý
	SELECT SPID,COUNT(*)AS SattýðýAraçSayýsý
	FROM SALE
	GROUP BY SPID
	HAVING SPID='400'

	--HER BÝR PERSONELÝN MAX. FÝYATA SATILAN ARACIN FÝYATI VE PERSONEL NO
	SELECT SPID,MAX(Sprice) AS Fiyat
	FROM SALE
	GROUP BY SPID

--MÝNÝMUM 2 TABLOYU KULLANAN SORGULAR
	--SATILMAYAN ARAÇLARIN SERÝAL NOLARINI LÝSTELEME
	SELECT C.SerialNO
	FROM CAR C
	LEFT JOIN SALE S
	ON S.SerialNO=C.SerialNO
	WHERE S.SerialNO IS NULL

	--HER BÝR MÜÞTERÝNÝN ADI, SOYADI VE ALDIKLARI ARAÇ SAYISI
	SELECT C.CustomerFName,C.CustomerLName,COUNT(*)AS AldýklarýAraçSayýsý
	FROM  CUSTOMER C
	LEFT JOIN SALE S
	ON S.CustomerID=C.CustomerID
	WHERE S.SerialNO IS NOT NULL
	GROUP BY C.CustomerFName,C.CustomerLName

	--SATILMAYAN PAKETLER
	SELECT M.PackageNO
	FROM CAR_PACKAGE C
	RIGHT JOIN MODEL_PACKAGE M
	ON M.PackageNO=C.PackageNO
	WHERE C.PackageNO IS NULL

	--333333333 SERÝAL NOLU ARACIN MODEL BÝLGÝLERÝ
	SELECT M.ModelNO,M.Manufacture,M.ModelName,M.Price
	FROM CAR C,MODEL M
	WHERE C.ModelNO=M.ModelNO AND C.SerialNO='333333333'

--MÝNÝMUM ÜÇ TABLOYU KULLANAN SORGULAR
	--MÜÞTERÝLERÝN ALDIÐI HER BÝR ARAÇ ÝÇN ÖDEDÝKLERÝ PAKET VE OPSÝYON FÝYATLARI
	SELECT K.CustomerFName,K.CustomerLName,C.SerialNO,(S.SPrice-M.Price)AS Fiyat
	FROM MODEL M,CAR C,SALE S,CUSTOMER K
	WHERE S.SerialNO=C.SerialNO AND C.ModelNO=M.ModelNO AND S.CustomerID=K.CustomerID

	--ASTRA MODELÝNE AÝT OPSÝYONLARIN ÝSÝM VE FÝYATLARI
	SELECT O.OptionName,O.OptionPrice
	FROM MODEL M,OPTIONS O,M_OPTIONS N
	WHERE M.ModelNO=N.ModelNO AND N.OptionNO=O.OptionNO AND M.ModelName='ASTRA'

	--400 NUMARALI PERSONELÝN SATTIÐI ARAÇLARA AÝT BÝLGÝLER
	SELECT SP.SPFName,SP.SPLName,M.Manufacture,M.ModelName,S.SerialNO,S.SPrice
	FROM SALE S,SALESPERSON SP,MODEL M, CAR C
	WHERE SP.SPID=S.SPID AND S.SerialNO=C.SerialNO AND C.ModelNO=M.ModelNO AND SP.SPID='400'
--ÝSTEKLER
	--3'TEN FAZLA OPSÝYONA SAHÝP ARAÇLARIN MARKA VE MODELLERÝ
	SELECT DISTINCT Manufacture,ModelName
	FROM MODEL
	WHERE ModelNO IN(	SELECT ModelNO
						FROM M_OPTIONS
						GROUP BY ModelNO
						HAVING COUNT(*)>3
					)	
	--HER BÝR SATIÞ ÝÇÝN MÜÞTERÝ VE ÝLÝÞKÝLÝ PERSONELLERÝN PERSONEL ÝSÝMLERÝNE GÖRE GRUPLANDIRILMASI		
	SELECT S.SPFName,S.SPLName,C.CustomerFName,C.CustomerLName
	FROM SALESPERSON S,CUSTOMER C,SALE K
	WHERE K.CustomerID=C.CustomerID AND K.SPID=S.SPID
	--ORDER BY S.SPFName,S.SPLName
	GROUP BY S.SPFName,S.SPLName,C.CustomerFName,C.CustomerLName
	
	--ÝKÝDEN FAZLA ARAÇ SATAN PERSONELLERÝN ÝSÝMLERÝ
	SELECT SPFName,SPLName
	FROM SALESPERSON
	WHERE SPID IN(	SELECT SPID
					FROM SALE
					GROUP BY SPID
					HAVING COUNT(*)>2
				 )

	--PAKETLERDE EN ÇOK TEKRAR EDEN OPSÝYONUN ÝSMÝ
	SELECT L.OptNO,L.OptionName,K.Sayý
	FROM (select max(a.x)AS Sayý from OPTIONS o full outer join (select count(*)as x,OptNO from P_OPTION group by OptNO) as a on o.OptionNO=a.OptNO) AS K,
		 (SELECT o.OptionName,count(*)as x,P.OptNO FROM P_OPTION p,OPTIONS o WHERE O.OptionNO=P.OptNO GROUP BY p.OptNO,o.OptionName) AS L
	WHERE K.SAYI=L.x